### PR TITLE
Gabriel

### PR DESCRIPTION
**Pull request by omega13a**
Added liveries from the offical FlightGear livery database as well as standardize livery file names (got rid of the -800 in the names of several files).

### CODE REVIEW

**Comment by FGDATA** [comment]
Hi @YV3399 @legoboyvdlp @it0uchpods 

Note this pull request'
It looks really good to me and you guys may want to merge,

I will stand for Gabriel and the team to review since this is coming to Gabriel's branch.

Quick question, just to make sure: is it livery compatible?

Best,
@IAHM-COL

**Comment by Octal450** [comment]
@FGDATA Looks fine here.

Merged.

Josh

**Comment by FGDATA** [comment]
nice job Josh

You are really fast !!!  that 's awesome

you guys may want to invite omega13b to your slack thing :P

I'll send him an FGMEMBERS invite too

Best,
@IAHM-COL

**Comment by Octal450** [comment]
@FGDATA Thanks! :) I try.

I'll send an invite.

I updated our dev /YV3399/737-800 with this changes aswel.

Josh

**Comment by YV3399** [comment]
Thanks for your job @omega13a.

Gabriel Hernandez

**Pull request merged**
